name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust the branch as per your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 629388610155.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t hello-world-python .
          docker tag hello-world-python:latest 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python:latest
          docker push 629388610155.dkr.ecr.us-east-1.amazonaws.com/hello-world-python:latest
        env:
          AWS_DEFAULT_REGION: us-east-1
